schema_version: 1

context:
  name: de-coachingangebote
  version: "0.1.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/de-coachingangebote-${{ version }}.tar.gz
  sha256: b3a4fa1ea0e7d3f44a6b76c0aaa3b879b8c599c393b7db5dcce10a77e7ad9948

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - poetry
  run:
    - python >=${{ python_min }}
    - python-dateutil
    - urllib3 >=1.25.3

tests:
  - python:
      imports:
        - deutschland.coachingangebote
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: "Bundesagentur für Arbeit: Coachingangebote API"
  license: Apache-2.0
  license_file:
    - LICENSE
  homepage: https://github.com/bundesAPI/coachingangebote-api

extra:
  recipe-maintainers:
    - jan-janssen
